# @package data

environments:
  TwoRoom:
    name: design_v0/tworoom_expert.lance
    split_manifest: design_v0/splits/tworoom.json
    frameskip: 5
    keys_to_load:
      - pixels
      - action
    keys_to_cache:
      - action
  PushT:
    name: design_v0/pusht_expert_train.h5
    split_manifest: design_v0/splits/pusht.json
    frameskip: 5
    keys_to_load:
      - pixels
      - action
    keys_to_cache:
      - action
  OGBCube:
    name: design_v0/ogbcube/cube_single_front_expert.lance
    split_manifest: design_v0/splits/ogbcube.json
    frameskip: 5
    keys_to_load:
      - pixels
      - action
    keys_to_cache:
      - action
