# @package data

environments:
  OGBCube:
    name: design_v0/ogbcube/cube_single_front_expert.lance
    split_manifest: design_v0/splits/ogbcube.json
    frameskip: 5
    keys_to_load:
      - pixels
      - action
    keys_to_cache:
      - action
