# @package data

environments:
  TwoRoom:
    name: design_v0/tworoom_expert.lance
    split_manifest: design_v0/splits/tworoom.json
    frameskip: 5
    keys_to_load:
      - pixels
      - action
    keys_to_cache:
      - action
